// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	// Copies every message strictly BEFORE the checkpoint message into a new
	// session, preserving original insertion order via the source rowid cut.
	// Each copy gets a freshly generated ID because messages.id is a global
	// PRIMARY KEY, so original IDs cannot be reused across sessions.
	CopyMessagesUpToCheckpoint(ctx context.Context, arg CopyMessagesUpToCheckpointParams) error
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	// A fork is a root session (parent_session_id NULL) that records its origin
	// in forked_from_session_id, so it shows up in ListSessions and remains
	// continuable while the lineage stays traceable.
	CreateForkedSession(ctx context.Context, arg CreateForkedSessionParams) (Session, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteFile(ctx context.Context, id string) error
	DeleteFileVersionsByID(ctx context.Context, ids []string) error
	DeleteMessage(ctx context.Context, id string) error
	DeleteMessagesFromCheckpoint(ctx context.Context, arg DeleteMessagesFromCheckpointParams) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionFiles(ctx context.Context, sessionID string) error
	DeleteSessionMessages(ctx context.Context, sessionID string) error
	GetAverageResponseTime(ctx context.Context) (int64, error)
	GetFile(ctx context.Context, id string) (File, error)
	GetFileByPathAndSession(ctx context.Context, arg GetFileByPathAndSessionParams) (File, error)
	GetFileRead(ctx context.Context, arg GetFileReadParams) (ReadFile, error)
	GetHourDayHeatmap(ctx context.Context) ([]GetHourDayHeatmapRow, error)
	GetLastAssistantMessageBySession(ctx context.Context, sessionID string) (Message, error)
	GetLastSession(ctx context.Context) (Session, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetRecentActivity(ctx context.Context) ([]GetRecentActivityRow, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	GetToolUsage(ctx context.Context) ([]GetToolUsageRow, error)
	GetTotalStats(ctx context.Context) (GetTotalStatsRow, error)
	GetUsageByDay(ctx context.Context) ([]GetUsageByDayRow, error)
	GetUsageByDayOfWeek(ctx context.Context) ([]GetUsageByDayOfWeekRow, error)
	GetUsageByHour(ctx context.Context) ([]GetUsageByHourRow, error)
	GetUsageByModel(ctx context.Context) ([]GetUsageByModelRow, error)
	ListAllUserMessages(ctx context.Context) ([]Message, error)
	// created_at is second-precision, so siblings created within the same second
	// would otherwise come back in undefined order. Tie-break on insertion order.
	ListChildSessions(ctx context.Context, parentSessionID sql.NullString) ([]Session, error)
	ListFilesByPath(ctx context.Context, path string) ([]File, error)
	ListFilesBySession(ctx context.Context, sessionID string) ([]File, error)
	// created_at is second-precision, so tie-break on insertion order.
	ListForks(ctx context.Context, forkedFromSessionID sql.NullString) ([]Session, error)
	ListLatestSessionFiles(ctx context.Context, sessionID string) ([]File, error)
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	// Messages at or after the checkpoint, ordered by insertion (rowid) so the cut
	// is exact even when created_at timestamps collide at second precision.
	ListMessagesFromCheckpoint(ctx context.Context, arg ListMessagesFromCheckpointParams) ([]Message, error)
	ListSessionReadFiles(ctx context.Context, sessionID string) ([]ReadFile, error)
	ListSessions(ctx context.Context) ([]Session, error)
	ListUserMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	RecordFileRead(ctx context.Context, arg RecordFileReadParams) error
	RenameSession(ctx context.Context, arg RenameSessionParams) error
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpdateSessionTitleAndUsage(ctx context.Context, arg UpdateSessionTitleAndUsageParams) error
}

var _ Querier = (*Queries)(nil)
